# Power Management
CONFIG_ZMK_SLEEP=y

# Wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Display Settings
CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Pointer events (Set to 'n' if you don't have a trackball/pointer)
CONFIG_ZMK_POINTING=n